## Упражнения по библиотеке Numpy

In [136]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [137]:
a = np.random.random(100)*100
print(a)

for idx, x in enumerate(a):
    if(3<x<8):
        a[idx]=x*(-1)

print(a)



[65.82861839 58.53152745 45.18556368 81.87900495 46.95398535 51.05701335
 30.51541322 68.63404573 90.53897359 18.42117983 16.51751138 54.33845858
 91.38370791 23.36532751 69.42069753 10.03978203 76.31544921  9.74551584
 58.26817987 78.19872566 72.49775819 21.91815485 53.38450978 53.05288969
 69.0387976  18.24129421  0.68903283 93.98372127 47.33603723 67.12116936
 51.77729572 50.74518712 53.304034    2.67812649 91.29909706 60.7604499
  0.4355986  89.2185279  46.15098423 23.10377093 67.88489209  6.91061769
 36.63408854 51.20997005 36.47115536 76.11622848 99.85020577 98.21949825
 61.21098277  9.79653176  7.19269329  2.72885937 12.92707596 67.42442462
 61.18343649 95.65773423 19.14679146 76.75869919 34.5507164  28.57651114
 11.28047894 51.38098139 43.07080546 92.4374291  32.90104986  6.91667547
  2.78333085 92.76317101 23.72883189 41.77103133 46.61484462 58.33918479
 67.72066902 35.8636328  78.04715698 89.34536589 92.32904814 49.74207509
 13.20413692 49.28251955 72.89149349 74.95677721 55.

**2.** Заменить максимальный элемент случайного массива на 0

In [138]:
a = np.random.random(40)*100
print(a)

max_index = np.argmax(a)
a[max_index] = 0

print(a)


[45.39469036 99.21733828 38.61219829 30.07726204 10.08515187  0.84578204
 27.12219869 73.76462226 73.47714511 79.66263127 73.75549688 98.23112361
 38.9460945  87.88852521 92.41515799 99.62048233 20.66506924 86.75352123
  6.83783729 95.00659897 33.68441327 85.9526658   4.7126088  14.1752589
 96.05849394 38.0059643   4.38578843 58.4884578   1.17664111 53.82546282
 44.63285667 68.76285576 70.9812126  14.9378671  70.52126643 50.96717182
 95.31945045 72.81409732 50.93667813 10.04043583]
[45.39469036 99.21733828 38.61219829 30.07726204 10.08515187  0.84578204
 27.12219869 73.76462226 73.47714511 79.66263127 73.75549688 98.23112361
 38.9460945  87.88852521 92.41515799  0.         20.66506924 86.75352123
  6.83783729 95.00659897 33.68441327 85.9526658   4.7126088  14.1752589
 96.05849394 38.0059643   4.38578843 58.4884578   1.17664111 53.82546282
 44.63285667 68.76285576 70.9812126  14.9378671  70.52126643 50.96717182
 95.31945045 72.81409732 50.93667813 10.04043583]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [139]:

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)
    
    ix = np.indices(shape, dtype=int) 
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

cartesian([[1,2,3,4,5], [6,7,8,9]])

array([[1, 6],
       [1, 7],
       [1, 8],
       [1, 9],
       [2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [3, 6],
       [3, 7],
       [3, 8],
       [3, 9],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 6],
       [5, 7],
       [5, 8],
       [5, 9]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [161]:
m1 = 8
n1 = 3
m2 = 2
n2 = 2

array1 = np.random.randint(0,11,(m1,n1))
print("Array 1:")
print(array1)
array2 = np.random.randint(0,11,(m2,n2))
print("Array 2:")
print(array2)

array3 = array1[...,np.newaxis,np.newaxis]==array2
rows = []
for idx, x in enumerate(array3.sum(axis=(1,3))):
    if x[0]>=1 and x[1]>=1:
        rows.append(idx)
print("Rows #:")
print(rows)

Array 1:
[[ 0  3  2]
 [ 2  2  4]
 [ 6  0  2]
 [ 4  9  0]
 [ 9 10  4]
 [ 9  8  7]
 [ 7  2 10]
 [ 8  1  9]]
Array 2:
[[10  2]
 [ 8  4]]
Rows #:
[1, 4]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [284]:
m = 10
n = 3
mtrx = np.random.randint(0,5,(m,n))
print("Start:")
print(mtrx)
idxs=[]
for i in range(len(mtrx)):
    print(mtrx[i][0]==mtrx[i][1]==mtrx[i][2])
    if(mtrx[i][0]==mtrx[i][1]==mtrx[i][2]): 
        idxs.append(i)
        print(i)
mtrx = np.delete(mtrx,idxs,axis=0)
print("Finish:")     
print(mtrx)

Start:
[[1 1 1]
 [4 4 3]
 [3 3 4]
 [4 0 0]
 [1 3 2]
 [2 0 1]
 [1 1 2]
 [0 0 4]
 [3 4 3]
 [0 4 3]]
True
0
False
False
False
False
False
False
False
False
False
Finish:
[[4 4 3]
 [3 3 4]
 [4 0 0]
 [1 3 2]
 [2 0 1]
 [1 1 2]
 [0 0 4]
 [3 4 3]
 [0 4 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [299]:
m = 10
n = 2

array = np.random.randint(0,5,(m,n))
print("Array")
print(array)
unique_array, idx = np.unique(array,axis=0,return_index=True)
result = unique_array[idx.argsort()]
print("Unique array")
print(result)

Array
[[2 4]
 [4 1]
 [0 4]
 [4 0]
 [2 1]
 [4 2]
 [1 1]
 [3 2]
 [4 2]
 [2 1]]
Unique array
[[2 4]
 [4 1]
 [0 4]
 [4 0]
 [2 1]
 [4 2]
 [1 1]
 [3 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [ ]:
# your code

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [ ]:
# your code

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
# your code

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
# your code

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
# your code

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [ ]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [ ]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [ ]:
# your code

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [ ]:
# your code

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [ ]:
# your code

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [ ]:
# your code

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [ ]:
# your code

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
# your code

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
# your code