## Упражнения по библиотеке Numpy

In [54]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [55]:
a = np.random.random(100)*100
print(a)

for idx, x in enumerate(a):
    if(3<x<8):
        a[idx]=x*(-1)

print(a)



[77.33341136 51.92536353 15.8256369  92.16897013 18.36024873 77.38009885
 71.99913049 98.27206357 35.5610121  12.39594797 18.8843927  21.50272727
 68.38522834 65.36888426 11.59936557 17.0364901  28.65877015 45.48918255
 30.81966824 86.91660962 74.59425227 97.04573314 48.10832716 24.8220681
 14.19784078 72.47904253 78.41353969 73.90763496  6.52534244 28.43659253
 36.4615389  95.16568044 76.06427853 49.9044228  70.12462306 37.20288247
 75.40289431 89.37307787 18.90025939 31.44552045 87.82653277 24.07688948
 11.04834937 33.44786046 63.88969293 71.37130753 37.79869516  3.60933253
 79.05972132 26.36089209 91.6344748  57.96454401  8.77526053 82.86879494
 30.61754665 88.07467575 61.28034589 32.11942038  0.73996173  3.71050058
 71.08878474  1.7786477  12.5159306  24.00529374  0.15913874 52.4634019
 66.99889925 23.80471359 66.42421481 58.41331252 36.50736444 38.9459111
 16.69749423 94.02473646 79.9499458  91.35356096 56.58301824 11.85296479
 18.94973116 37.05174782 83.32109086 61.94036038 51.21

**2.** Заменить максимальный элемент случайного массива на 0

In [56]:
a = np.random.random(40)*100
print(a)

max_index = np.argmax(a)
a[max_index] = 0

print(a)


[61.00845125 81.9047022  81.46715637 55.21317414  8.48606639 69.2155379
 22.35772054 11.66715675  0.98559064 67.0858833  61.66700357  2.19818765
 62.30717061 16.40380993 51.7319112  63.74125167 96.14122033 46.37610115
 30.86332363 69.56773203 50.18060059 72.96343755 74.3424238  95.08013891
 60.4140837  72.6996847  41.45608458  6.86117696 76.17681714 81.93134544
 39.52492752 40.00416926 34.68042803 70.52576307 14.46351207 58.88933812
 33.67117584 53.04173675  2.64468655 72.76241166]
[61.00845125 81.9047022  81.46715637 55.21317414  8.48606639 69.2155379
 22.35772054 11.66715675  0.98559064 67.0858833  61.66700357  2.19818765
 62.30717061 16.40380993 51.7319112  63.74125167  0.         46.37610115
 30.86332363 69.56773203 50.18060059 72.96343755 74.3424238  95.08013891
 60.4140837  72.6996847  41.45608458  6.86117696 76.17681714 81.93134544
 39.52492752 40.00416926 34.68042803 70.52576307 14.46351207 58.88933812
 33.67117584 53.04173675  2.64468655 72.76241166]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [57]:

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)
    
    ix = np.indices(shape, dtype=int) 
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

cartesian([[1,2,3,4,5], [6,7,8,9]])

array([[1, 6],
       [1, 7],
       [1, 8],
       [1, 9],
       [2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [3, 6],
       [3, 7],
       [3, 8],
       [3, 9],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 6],
       [5, 7],
       [5, 8],
       [5, 9]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [79]:
m1 = 8
n1 = 3
m2 = 2
n2 = 2

array1 = np.random.randint(0,11,(m1,n1))
print("Array 1:")
print(array1)
array2 = np.random.randint(0,11,(m2,n2))
print("Array 2:")
print(array2)

array3 = array1[...,np.newaxis,np.newaxis]==array2
rows = []
for idx, x in enumerate(array3.sum(axis=(1,3))):
    if x[0]>=1 and x[1]>=1:
        rows.append(idx)
print("Rows #:",rows)


Array 1:
[[1 2 0]
 [1 1 7]
 [1 3 8]
 [9 2 5]
 [2 7 6]
 [6 4 4]
 [9 7 5]
 [7 2 8]]
Array 2:
[[3 9]
 [5 6]]
Rows #: [3, 6]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [91]:
m = 10
n = 3
mtrx = np.random.randint(0,5,(m,n))
print("Start:")
print(mtrx)
idxs=[]
for i in range(len(mtrx)):
    if(mtrx[i][0]==mtrx[i][1]==mtrx[i][2]): 
        idxs.append(i)
mtrx = np.delete(mtrx,idxs,axis=0)
print("Finish:")     
print(mtrx)

Start:
[[2 4 4]
 [3 3 0]
 [1 0 0]
 [3 2 4]
 [0 1 1]
 [2 2 2]
 [2 2 3]
 [0 4 2]
 [0 1 3]
 [1 3 4]]
Finish:
[[2 4 4]
 [3 3 0]
 [1 0 0]
 [3 2 4]
 [0 1 1]
 [2 2 3]
 [0 4 2]
 [0 1 3]
 [1 3 4]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [60]:
m = 10
n = 2

array = np.random.randint(0,5,(m,n))
print("Array")
print(array)
unique_array, idx = np.unique(array,axis=0,return_index=True)
result = unique_array[idx.argsort()]
print("Unique array")
print(result)

Array
[[3 2]
 [4 2]
 [3 3]
 [2 2]
 [3 4]
 [0 1]
 [2 4]
 [3 1]
 [1 2]
 [0 1]]
Unique array
[[3 2]
 [4 2]
 [3 3]
 [2 2]
 [3 4]
 [0 1]
 [2 4]
 [3 1]
 [1 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [61]:
# Вариант 1:

Y = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
d = min(len(Y),len(Y[0]))
result1 = 1
for i in range(d):
    if(Y[i][i]!=0):
        result1 *= Y[i][i]
print(result1)

# Вариант 2:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
result2 = np.prod(np.diag(X)[np.diag(X)!=0])
print(result2)

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [62]:
# Вариант 1:
x1 = [1,2,2,4]
y1 = [4,2,1,2]

def are_equal1(x,y):
    if(len(x) != len(y)):
        return False
    x.sort()
    y.sort()
    for i in range(len(x)):
        if(x[i] != y[i]):
            return False
    return True

print(are_equal1(x1, y1))
    
# Вариант 2:

x2 = np.array([1,2,2,4])
y2 = np.array([4,2,1,2])

def are_equal2(x,y):
    x_elements, x_counts = np.unique(x,return_counts=True)
    y_elements, y_counts = np.unique(y,return_counts=True)
    if(np.shape(x_elements) != np.shape(y_elements)):
        return False
    if(np.any(x_elements != y_elements) or np.any(x_counts != y_counts)):
        return False
    return True

print(are_equal2(x2,y2))


True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [63]:
# Вариант 1:
x1 = [6, 2, 0, 3, 0, 0, 5, 7, 0]

def max_element_before_zero1(x):
    after_zero_list = []
    for i in range(1,len(x)):
        if(x[i-1]==0):
            after_zero_list.append(x[i])
    return max(after_zero_list)
    
print(max_element_before_zero1(x1))

# Вариант 1:
x2 = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

def max_element_before_zero2(x):
    zero = x==0
    return np.max(x[1:][zero[:-1]])

print(max_element_before_zero2(x2))

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [64]:
# Вариант 1:
x1 = [2, 2, 2, 3, 3, 3, 5]

def run_length_encoding(x):
    values = [x[0]]
    counts = []
    counter = 1
    for i in range(1,len(x1)):
        if(x1[i-1] == x1[i]):
            counter+=1
        else:
            values.append(x[i])
            counts.append(counter)
            counter = 1
    counts.append(counter)
    return(values,counts)

print(run_length_encoding(x1))




# Вариант 2:
x2 = np.array([2, 2, 2, 3, 3, 3, 5])

print(np.unique(x2,return_counts=True))


([2, 3, 5], [3, 3, 1])
(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [65]:
# Вариант 1:
x1=[[1,2],[3,4]]
y1=[[5,6],[7,8]]

import math
def evklid_distance1(x,y):
    evklid_mtrx = []
    for i in range(len(x)):
        z = []
        for j in range(len(y)):
            dist = 0
            for k in range(len(x[0])):
                dist += (x[i][k]-y[j][k])**2
            z.append(math.sqrt(dist))
        evklid_mtrx.append(z)
    return evklid_mtrx

print(evklid_distance1(x1,y1))


# Вариант 2:
x2=np.array([[1,2],[3,4]])
y2=np.array([[5,6],[7,8]])

def evklid_distance2(x,y):
    return np.sqrt(np.sum((x[:, np.newaxis] - y) ** 2, axis=-1))

print(evklid_distance2(x2,y2))

from scipy.spatial.distance import cdist
import timeit

size = 10
loops = 10

M = np.random.randint(-10,10,(size, size))
N = np.random.randint(-10,10,(size, size))
start = timeit.default_timer()
for i in range(0,loops,1):
    evklid_distance1(M,N)
end = timeit.default_timer()
print("Not numpy: ",(end-start)*1000/loops, "msec")

start = timeit.default_timer()
for i in range(0,loops,1):
    evklid_distance2(M,N)
end = timeit.default_timer()
print("Numpy: ",(end-start)*1000/loops, "msec")

start = timeit.default_timer()
for i in range(0,loops,1):
   cdist(M,N,metric='euclidean')
end = timeit.default_timer()
print("Cdist: ",(end-start)*1000/loops, "msec")



[[5.656854249492381, 8.48528137423857], [2.8284271247461903, 5.656854249492381]]
[[5.65685425 8.48528137]
 [2.82842712 5.65685425]]
Not numpy:  0.619308400018781 msec
Numpy:  0.09054999991349177 msec
Cdist:  0.07861670001148013 msec


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [66]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [67]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [68]:
average_calories = np.average(calorie_stats)
print(average_calories)

106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [69]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [70]:
median_calories = np.median(calorie_stats_sorted)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [71]:
q = 98
step = 2
while np.percentile(calorie_stats_sorted,q)>=60:
    print("Percentile ",q,":",np.percentile(calorie_stats_sorted,q))
    q-=step

nth_percentile = q+step
print("Result:",nth_percentile)

Percentile  98 : 150.0
Percentile  96 : 140.0
Percentile  94 : 140.0
Percentile  92 : 130.0
Percentile  90 : 124.00000000000006
Percentile  88 : 120.0
Percentile  86 : 120.0
Percentile  84 : 120.0
Percentile  82 : 120.0
Percentile  80 : 120.0
Percentile  78 : 120.0
Percentile  76 : 110.0
Percentile  74 : 110.0
Percentile  72 : 110.0
Percentile  70 : 110.0
Percentile  68 : 110.0
Percentile  66 : 110.0
Percentile  64 : 110.0
Percentile  62 : 110.0
Percentile  60 : 110.0
Percentile  58 : 110.0
Percentile  56 : 110.0
Percentile  54 : 110.0
Percentile  52 : 110.0
Percentile  50 : 110.0
Percentile  48 : 110.0
Percentile  46 : 110.0
Percentile  44 : 110.0
Percentile  42 : 110.0
Percentile  40 : 110.0
Percentile  38 : 100.0
Percentile  36 : 100.0
Percentile  34 : 100.0
Percentile  32 : 100.0
Percentile  30 : 100.0
Percentile  28 : 100.0
Percentile  26 : 100.0
Percentile  24 : 100.0
Percentile  22 : 100.0
Percentile  20 : 100.0
Percentile  18 : 100.0
Percentile  16 : 91.6
Percentile  14 : 90.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [72]:
more_calories = np.count_nonzero(calorie_stats_sorted > 60)/calorie_stats_sorted.size
print(more_calories, "%")


0.961038961038961 %


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [73]:
calorie_std = np.std(calorie_stats_sorted)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [74]:
# Из рассчетов видно, что данные довольно сильно разбросаны. Стандартное отклоение около 20 при среднем 106. Значение средней величины не стоит использовать при маркетинге CrunchieMunchies. При оценке среднего стоит полагаться на медиану.
# Наиболее выигрышным выглядит использование процента хлопьев, калорийность которых превышает калорийность CrunchieMunchies. (96%)